name: Build and Publish - TEST

on:
  push:

jobs:
  test:
    uses: .github/workflows/test.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Setup Elm ğŸŒ³
        uses: jorelali/setup-elm@v5
        with:
          elm-version: '0.19.1'

      - name: Install ğŸ“¦ï¸
        run: npm ci

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Move Files ğŸšš
        # Add files from dist (which vite makes) to static (which holds all of our other compiled files)
        run: mv dist/* static
