name: Build and Publish 

on: 
  push:
    branches:
      - main 
      - remote-website-add

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup Elm ğŸŒ³
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - name: Install and Build ğŸ”§
        run: |
          npm ci
          npm run build
      
      - name: Move Files ğŸšš
        # Add files from build (which create-elm-app made) to static (which holds all of our other compiled files)
        run: mv build/* static

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: static # The folder the action should deploy.