name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - src/**/*
      - package*.json
      - index.html
      - index.js
      - main.css
      - .github/workflows/gh-pages-publish.yml # This file
      - static/**/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Setup Elm ğŸŒ³
        uses: jorelali/setup-elm@v4
        with:
          elm-version: '0.19.1'

      - name: Install ğŸ“¦ï¸
        run: npm ci

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Move Files ğŸšš
        # Add files from dist (which vite makes) to static (which holds all of our other compiled files)
        run: mv dist/* static

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: static # The folder the action should deploy.
          # https://github.com/actions/checkout/discussions/479#discussioncomment-625461
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
