name: Test

on: 
  push:
    branches:
      - main
    paths:
      - src/**/*
      - package*.json
      - index.html
      - index.js
      - main.css
      - .github/workflows/test.yml # This file
      - vite.config.js 
  pull_request:
    branches:
      - main
    paths:
      - src/**/*
      - package*.json
      - index.html
      - index.js
      - main.css
      - .github/workflows/test.yml # This file
      - vite.config.js
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Setup Elm ğŸŒ³
        uses: jorelali/setup-elm@v4
        with:
          elm-version: '0.19.1'

      - name: Install ğŸ“¦ï¸
        run: npm i

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Tests ğŸ§ª
        uses: cypress-io/github-action@v5.2.0 # use the explicit version number
        with:
          build: npm run build
          start: npm run dev