name: Test

on: 
  push:
    branches:
      - main
    paths:
      - src/**/*
      - package*.json
      - index.html
      - index.js
      - main.css
      - .github/workflows/test.yml # This file
      - vite.config.js 
  pull_request:
    branches:
      - main
    paths:
      - src/**/*
      - package*.json
      - index.html
      - index.js
      - main.css
      - .github/workflows/test.yml # This file
      - vite.config.js
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    container: node16.18.0-chrome90-ff88
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      
      - name: Setup Elm ğŸŒ³
        uses: jorelali/setup-elm@v4
        with:
          elm-version: '0.19.1'

      - name: Save build folder ğŸ“¦ï¸
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

      - name: Cypress install
        uses: cypress-io/github-action@v5.2.0 # use the explicit version number
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

  test:
    runs-on: ubuntu-latest
    container: node16.18.0-chrome90-ff88
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.2.0 # use the explicit version number
        with:
          # Specify Browser since container image is compile with Firefox
          browser: chrome
          build: npm run build
